include:
  - project: 'esperantotech/software/gitlab-ci-common'
    ref: a782d2470d791ff3340dc0468cc6cf7c8956e3fd
    file:
      - rules/generic-workflow-conan.yaml
      - pods/nano-pod.yaml
      - pods/large-pod.yaml
      - jobs/generic-k8s-job.yaml
      - rules/exec_maybe_interactively.yaml
  - project: 'esperantotech/software/gitlab-ci-common'
    ref: master
    file:
      - 'jobs/conan-jobs.yaml'

stages:
  - smoke
  - codequality
  - test
  
default:
  interruptible: true

variables:
  ET_SW_DEVELOP_DOCKER_IMAGE:
    value: docker-sw-team.sc-artifactory1.esperanto.ai/convoke/ubuntu-22.04-et-sw-develop-stack:1.6.4
  ET_SDK_HOME:
    value: '/usr/local/esperanto'
  CMAKE_TOOLCHAIN_FILE:
    value: '${ET_SDK_HOME}/.builds/host/conan_toolchain.cmake'
  PYTEST_OPTIONS:
    description: Common pytest options
    value: --log-cli-level=INFO --tb=short --quiet --basetemp=$CI_JOB_ID.tmp --junitxml=$CI_JOB_ID.xml --durations=0

# Only run job in these cases:
# - if there is a MR open
.development_job:
  rules:
    - &development_job_rule
      if: ($CI_PIPELINE_SOURCE == "merge_request_event") && ($CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH)

clang-format:
  extends:
    - .template_job
    - .pod_nano
  image: '${ET_SW_DEVELOP_DOCKER_IMAGE}'
  stage: smoke
  rules:
    - *development_job_rule
  variables:
    CMD_SCRIPT: |
      source ${ET_SDK_HOME}/.builds/host/conanrun.sh
      git fetch origin $CI_DEFAULT_BRANCH
      git clang-format --diff origin/$CI_DEFAULT_BRANCH -- * | grep -e "clang-format did not modify any files$" -e "^no modified files to format$"

build:sonarqube-check:
  extends:
    - .pod_large
  stage: codequality
  image: '${ET_SW_DEVELOP_DOCKER_IMAGE}'
  needs: []
  tags:
    - k8s
  rules:
    - if: ($CI_PIPELINE_SOURCE == "merge_request_event") && ($CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH)
      allow_failure: false # TODO: change to 'false' once analysis are verified correct & stable
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      allow_failure: true
    - if: $CI_COMMIT_TAG
      allow_failure: true
  variables:
    GIT_STRATEGY: clone
    GIT_DEPTH: "0"  # Tells git to fetch all the branches of the project, required by the analysis task
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  # Defines the location of the analysis task cache
    SONAR_BUILD_WRAPPER_URL: "https://sc-sonarq01.esperanto.ai/static/cpp"
    SONAR_SCANNER_URL: "https://binaries.sonarsource.com/Distribution/sonar-scanner-cli"
    SONAR_SCANNER_ARCHIVE_NAME: "sonar-scanner-cli-4.8.0.2856-linux.zip"
    SONAR_SCANNER_UNZIPED_NAME: "sonar-scanner-4.8.0.2856-linux"
    SONAR_BUILD_WRAPPER: "build-wrapper-linux-x86"
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  before_script:
    - sudo apt-get update -qq
    - sudo apt-get install -qq -y --no-install-recommends zip unzip
    - wget ${SONAR_BUILD_WRAPPER_URL}/${SONAR_BUILD_WRAPPER}.zip
    - unzip ${SONAR_BUILD_WRAPPER}.zip
    - wget ${SONAR_SCANNER_URL}/${SONAR_SCANNER_ARCHIVE_NAME}
    - unzip ${SONAR_SCANNER_ARCHIVE_NAME}
    - export PATH=$PATH:$PWD/${SONAR_BUILD_WRAPPER}:$PWD/${SONAR_SCANNER_UNZIPED_NAME}/bin
    - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PWD/${SONAR_BUILD_WRAPPER}:$PWD/${SONAR_SCANNER_UNZIPED_NAME}/lib
  script:
    - cmake -S models/image-classifier/c++ -B .ci/sonarqube/build -DCMAKE_TOOLCHAIN_FILE=/usr/local/esperanto/.builds/host/conan_toolchain.cmake -DCMAKE_BUILD_TYPE=Release -G "Unix Makefiles"
    - build-wrapper-linux-x86-64 --out-dir build_wrapper_output_directory make -C .ci/sonarqube/build clean all
    - sonar-scanner
    
###############################################################################
###############################################################################
###############################################################################

.tests:common:
  extends:
    - .pod_large
    - .template_job
  stage: test
  rules:
    - *development_job_rule
  variables:
    ET_SDK_HOME: /usr/local/esperanto
    TEMP_DIR: temp
    TIMEOUT: 30m
    GLOG_minloglevel: 2 # Reduce Glow & Neuralizer verbosity ..
    BUILD_PATH: models/image-classifier/c++/build
    CMD_SETUP_EXTRA_DEPS: |
      # Download models
      sudo apt-get install -y ffmpeg libsm6 libxext6 --no-install-recommends
      python3 -m pip install -r requirements.txt --extra-index-url https://sc-artifactory1.esperanto.ai/artifactory/api/pypi/pypi-virtual/simple
      artifacts_mgr_client --inputfile artifacts/models.yaml --artifactpath ${CI_PROJECT_DIR}/DownloadArtifactory

    CMD_BUILD: | 
      if [ $API_TYPE == "C++" ]; then
        mkdir -p $$BUILD_PATH
        cd $$BUILD_PATH
        cmake -S .. -B . -DCMAKE_TOOLCHAIN_FILE="${ET_SDK_HOME}/.builds/host/conan_toolchain.cmake" -DCMAKE_BUILD_TYPE=Release -G Ninja
        cmake --build .
        cd -
      fi

    CMD_SCRIPT: |
      source ${ET_SDK_HOME}/.builds/host/conanrun.sh

      if [ $API_TYPE == "C++" ]; then
        cd $$BUILD_PATH
        ./mnist  -a ${CI_PROJECT_DIR}/DownloadArtifactory -mf ${CI_PROJECT_DIR}/models/image-classifier/c++/model-mnist-desc.json -v
      else
        python3 models/image-classifier/python/mnist.py --artifacts DownloadArtifactory
        #python3 models/image-classifier/python/resnet50.py --artifacts DownloadArtifactory
        python3 models/image-classifier/python/mobilenet.py --artifacts DownloadArtifactory
        python3 models/image-classifier/python/vgg16.py --artifacts DownloadArtifactory
      fi



tests:image-classification:python:sw-sysemu:
  extends:
    - .tests:common
  image:
    name: ${ET_SW_DEVELOP_DOCKER_IMAGE}
  variables:
    DEVICE_TYPE: sysemu   
    ORT_ETGLOW_DEVICE_TYPE: sysemu
    TIMEOUT: 90m

tests:image-classification:python:silicon:
  extends:
    - .tests:common
  image:
    name: ${ET_SW_DEVELOP_DOCKER_IMAGE}
    entrypoint: [""]
  variables:
    DEVICE_TYPE: silicon
    ORT_ETGLOW_DEVICE_TYPE: silicon
  tags:
    - silicon
    - 1-card-silicon
    - mv-gb-swci01

tests:image-classification:c++:sw-sysemu:
  extends:
    - .tests:common
  image:
    name: ${ET_SW_DEVELOP_DOCKER_IMAGE}
  variables:
    DEVICE_TYPE: sysemu
    ORT_ETGLOW_DEVICE_TYPE: sysemu
    API_TYPE: C++
  
tests:image-classification:c++:silicon:
  extends:
    - .tests:common
  image:
    name: ${ET_SW_DEVELOP_DOCKER_IMAGE}
    entrypoint: [""]
  variables:
    DEVICE_TYPE: silicon
    ORT_ETGLOW_DEVICE_TYPE: silicon    
    API_TYPE: C++
  tags:
    - silicon
    - 1-card-silicon
    - mv-gb-swci01